version: '3.7'
x-refs:
  sparkconf: &sparkconf
    image: spark-local:latest
    build:
      context: .
    working_dir: /opt/wd
    volumes:
      - .:/opt/wd
services:
  master:
    <<: *sparkconf
    command: ./runserver.sh master
    environment:
      MASTER: spark://master:7077
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    restart: always
  worker1:
    <<: *sparkconf
    command: ./runserver.sh worker spark://master:7077
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081
    depends_on:
      - master
    restart: always
  worker2:
    <<: *sparkconf
    command: ./runserver.sh worker spark://master:7077
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8082:8082
    depends_on:
      - master
    restart: always
networks:
  default:
    name: docker-spark-net
